// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH6aWcUM0FBtqmDWS1f9nY0cFqGemXYLg',
    appId: '1:198212150595:web:6545b39f923a42279fbbf6',
    messagingSenderId: '198212150595',
    projectId: 'compostcare',
    authDomain: 'compostcare.firebaseapp.com',
    storageBucket: 'compostcare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH00KTC36-1389ayBVM1TOL50m5uCmVLA',
    appId: '1:198212150595:android:6edad57ebc1caa919fbbf6',
    messagingSenderId: '198212150595',
    projectId: 'compostcare',
    storageBucket: 'compostcare.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYq7XJ89QLTA5YU5kWxLubjABULzP20Yk',
    appId: '1:198212150595:ios:59bc776a6df45b609fbbf6',
    messagingSenderId: '198212150595',
    projectId: 'compostcare',
    storageBucket: 'compostcare.firebasestorage.app',
    iosBundleId: 'com.example.compostcare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYq7XJ89QLTA5YU5kWxLubjABULzP20Yk',
    appId: '1:198212150595:ios:59bc776a6df45b609fbbf6',
    messagingSenderId: '198212150595',
    projectId: 'compostcare',
    storageBucket: 'compostcare.firebasestorage.app',
    iosBundleId: 'com.example.compostcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH6aWcUM0FBtqmDWS1f9nY0cFqGemXYLg',
    appId: '1:198212150595:web:715b7a694251871e9fbbf6',
    messagingSenderId: '198212150595',
    projectId: 'compostcare',
    authDomain: 'compostcare.firebaseapp.com',
    storageBucket: 'compostcare.firebasestorage.app',
  );
}
